version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: internportal
      MYSQL_USER: django_user
      MYSQL_PASSWORD: ranjith@2005
    ports:
      - "3307:3306"
    volumes:
      - intern_ips_db_data:/var/lib/mysql

  web:
    build: .
    command: 
      sh -c "python manage.py migrate &&
             gunicorn intern_site.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  intern_ips_db_data:
  static_volume:
  media_volume:
